fix: initramfs types

diff --git a/mkobsidianiso b/mkobsidianiso
--- a/mkobsidianiso
+++ b/mkobsidianiso
@@ -74,11 +74,46 @@ detect_kernel() {
     rootfs="$mount_point"
   fi
   local kernel=$(ls "$rootfs/boot/vmlinuz-"* 2>/dev/null | head -n1 | xargs basename | sed 's/vmlinuz-//')
+if [[ -z "$kernel" ]]; then
+  kernel=$(ls "$rootfs/boot/vmlinuz"* 2>/dev/null | head -n1 | xargs basename | sed 's/vmlinuz[-]*//')
+fi
   if $mount_needed; then
     umount "$mount_point"
   fi
   [[ -z "$kernel" ]] && error "Could not detect kernel version. Use -k to specify manually."
   echo "$kernel"
+}
+
+detect_initramfs_format() {
+  local rootfs="$1"
+  local kernel="$2"
+  local mount_needed=false
+  local mount_point=""
+  if [[ -f "$rootfs" ]]; then
+    mount_point="$WORKDIR/detect_mount"
+    mkdir -p "$mount_point"
+    mount -o loop,ro "$rootfs" "$mount_point" 2>/dev/null || error "Failed to mount $rootfs for initramfs detection"
+    mount_needed=true
+    rootfs="$mount_point"
+  fi
+  local initramfs_format=""
+  if [[ -f "$rootfs/boot/initramfs-$kernel.img" ]]; then
+    initramfs_format="initramfs"
+  elif [[ -f "$rootfs/boot/initrd-$kernel.img" ]]; then
+    initramfs_format="initrd"
+  elif [[ -f "$rootfs/boot/initramfs-$kernel" ]]; then
+    initramfs_format="initramfs_no_ext"
+  elif [[ -f "$rootfs/boot/initrd-$kernel" ]]; then
+    initramfs_format="initrd_no_ext"
+  elif [[ -f "$rootfs/boot/initramfs.img-$kernel" ]]; then
+    initramfs_format="initramfs_img_prefix"
+  elif [[ -f "$rootfs/boot/initrd.img-$kernel" ]]; then
+    initramfs_format="initrd_img_prefix"
+  fi
+  if $mount_needed; then
+    umount "$mount_point"
+  fi
+  echo "$initramfs_format"
 }
 
 extract_modules() {
@@ -300,6 +335,7 @@ INITEOF
 create_grub_cfg() {
   local dest="$1"
   local kernel="$2"
+  local rootfs="$3"
   local toramline=""
   local nontoramline=""
   if [[ "$ENABLE_TORAM" == "1" ]]; then
@@ -309,6 +345,17 @@ create_grub_cfg() {
     toramline=""
     nontoramline="obsidian.toram"
   fi
+  local initramfs_format=$(detect_initramfs_format "$rootfs" "$kernel")
+  [[ -z "$initramfs_format" ]] && error "Could not detect initramfs format for kernel $kernel"
+  local initrd_path=""
+  case "$initramfs_format" in
+    "initramfs") initrd_path="/boot/initramfs-$kernel.img" ;;
+    "initrd") initrd_path="/boot/initrd-$kernel.img" ;;
+    "initramfs_no_ext") initrd_path="/boot/initramfs-$kernel" ;;
+    "initrd_no_ext") initrd_path="/boot/initrd-$kernel" ;;
+    "initramfs_img_prefix") initrd_path="/boot/initramfs.img-$kernel" ;;
+    "initrd_img_prefix") initrd_path="/boot/initrd.img-$kernel" ;;
+  esac
   cat >"$dest" <<EOF
 set default=0
 set timeout=10
@@ -320,12 +367,12 @@ menuentry "$DISTRO" {
     echo "=> loading linux"
     linux (loop0)/boot/vmlinuz-$kernel root=LABEL=OBOS_$ISO_NAME rootfstype=iso9660 ro $toramline $EXTRA_BOOT_OPT
     echo "=> loading initramfs"
-    initrd (loop0)/boot/initramfs-$kernel.img
+    initrd (loop0)$initrd_path
     echo "=> booting"
     boot
 }
 
-submenu 'Advanced ($DISTRO)' {
+submenu 'Advanced Options for $DISTRO' {
     menuentry "$DISTRO (Safe Mode)" {
         echo "=> finding system image"
         search --no-floppy --set=root --file /live/system.sfs
@@ -334,7 +381,7 @@ submenu 'Advanced ($DISTRO)' {
         echo "=> loading linux"
         linux (loop0)/boot/vmlinuz-$kernel root=LABEL=OBOS_$ISO_NAME ro obsidian.safemode obsidian.debug $EXTRA_BOOT_OPT
         echo "=> loading initramfs"
-        initrd (loop0)/boot/initramfs-$kernel.img
+        initrd (loop0)$initrd_path
         echo "=> booting"
         boot
     }
@@ -347,7 +394,7 @@ submenu 'Advanced ($DISTRO)' {
         echo "=> loading linux"
         linux (loop0)/boot/vmlinuz-$kernel root=LABEL=OBOS_$ISO_NAME ro $nontoramline $EXTRA_BOOT_OPT
         echo "=> loading initramfs"
-        initrd (loop0)/boot/initramfs-$kernel.img
+        initrd (loop0)$initrd_path
         echo "=> booting"
         boot
     }
@@ -360,7 +407,7 @@ submenu 'Advanced ($DISTRO)' {
         echo "=> loading linux"
         linux (loop0)/boot/vmlinuz-$kernel root=LABEL=OBOS_$ISO_NAME ro obsidian.debug $EXTRA_BOOT_OPT
         echo "=> loading initramfs"
-        initrd (loop0)/boot/initramfs-$kernel.img
+        initrd (loop0)$initrd_path
         echo "=> booting"
         boot
     }
@@ -373,7 +420,7 @@ submenu 'Advanced ($DISTRO)' {
         echo "=> loading linux"
         linux (loop0)/boot/vmlinuz-$kernel root=LABEL=OBOS_$ISO_NAME ro nomodeset $EXTRA_BOOT_OPT
         echo "=> loading initramfs"
-        initrd (loop0)/boot/initramfs-$kernel.img
+        initrd (loop0)$initrd_path
         echo "=> booting"
         boot
     }
@@ -511,7 +558,7 @@ main() {
   info "Creating init script..."
   create_init_script "$iso_root/sbin/init"
   info "Creating GRUB configuration..."
-  create_grub_cfg "$iso_root/boot/grub/grub.cfg" "$kernel_version"
+  create_grub_cfg "$iso_root/boot/grub/grub.cfg" "$kernel_version" "$rootfs"
   info "Adding extra binaries"
   cp $BINARIES "$iso_root/extras/binaries/" || true
   info "Building ISO with grub-mkrescue..."
